language: node_js
node_js:
 - "6"
addons:
  firefox: latest
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
 - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
 - if [ "$TRAVIS_EVENT_TYPE" != "cron" ] || [[ "$BRANCH" == *"parser"* ]]; then npm run coverage && codecov -f .coverage/coverage-final.json -f .coverage/lcov.info; fi
 - if [[ "$BRANCH" == *"parser"* ]]; then npm run testManual; fi
