language: node_js
node_js:
 - "6"
addons:
  firefox: latest
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
 - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then npm run testManual; fi
 - npm run coverage
 - codecov -f .coverage/coverage-final.json -f .coverage/lcov.info
